import { Canvas, ThreeEvent, useFrame, useThree } from '@react-three/fiber'
import { Bounds, Environment, Grid, OrbitControls, TransformControls, useGLTF } from '@react-three/drei'
import { Suspense, useCallback, useEffect, useRef, useState } from 'react'
import type { ChangeEvent, FormEvent } from 'react'
import * as THREE from 'three'
import { GLTFExporter } from 'three/examples/jsm/exporters/GLTFExporter.js'
import { publicModels } from './modelCatalog'
import KeyframeTimeline from './KeyframeTimeline'
import './styles.css'

type TransformMode='translate'|'rotate'|'scale'; type TransformSpace='world'|'local'; type SelectedObject=THREE.Object3D
type EnvironmentPreset='studio'|'city'|'sunset'|'dawn'|'night'|'warehouse'|'forest'|'apartment'
type MaterialLike=THREE.MeshStandardMaterial|THREE.MeshPhysicalMaterial
type MaterialSnapshot={color:string;roughness:number;metalness:number;opacity:number;transparent:boolean}
type ObjectSnapshot={object:THREE.Object3D;position:THREE.Vector3;quaternion:THREE.Quaternion;scale:THREE.Vector3;material?:MaterialSnapshot}
type HistoryEntry={before:ObjectSnapshot;after:ObjectSnapshot}; type ProjectMaterial={color:string;roughness:number;metalness:number;opacity:number}
type ProjectObject={key:string;position:[number,number,number];quaternion:[number,number,number,number];scale:[number,number,number];material?:ProjectMaterial}
type ProjectFile={version:1;type:'three-playground-project';savedAt:string;model?:{source:'url';url:string;name:string};scene:{fov:number;ambientIntensity:number;keyLightIntensity:number;keyLightPosition:[number,number,number];fillLightIntensity:number;environmentEnabled:boolean;environmentPreset:EnvironmentPreset;environmentIntensity:number;objects:ProjectObject[]}}
type ModelProps={url:string;onSelect:(o:THREE.Object3D)=>void;onLoaded:(o:THREE.Object3D)=>void;onAnimations:(clips:THREE.AnimationClip[])=>void}
type SceneSettingsProps={fov:number;resetCamera:number;ambientIntensity:number;keyLightIntensity:number;keyLightPosition:[number,number,number];fillLightIntensity:number;environmentEnabled:boolean;environmentPreset:EnvironmentPreset;environmentIntensity:number}
const resourceUrls=new Map<string,string>()
function resolveResource(url:string){const n=url.split('?')[0].split('#')[0];for(const c of[n,n.replace(/^\.\//,''),decodeURIComponent(n)]){const d=resourceUrls.get(c);if(d)return d;const b=c.split('/').pop();if(b&&resourceUrls.has(b))return resourceUrls.get(b)!}return url}
function configureLoader(loader:{manager:THREE.LoadingManager}){loader.manager.setURLModifier(resolveResource)}
function materialFor(mesh:THREE.Mesh):MaterialLike|null{const m=Array.isArray(mesh.material)?mesh.material[0]:mesh.material;return m instanceof THREE.MeshStandardMaterial||m instanceof THREE.MeshPhysicalMaterial?m:null}
function captureSnapshot(o:THREE.Object3D):ObjectSnapshot{const s={object:o,position:o.position.clone(),quaternion:o.quaternion.clone(),scale:o.scale.clone()} as ObjectSnapshot;if(o instanceof THREE.Mesh){const m=materialFor(o);if(m)s.material={color:`#${m.color.getHexString()}`,roughness:m.roughness,metalness:m.metalness,opacity:m.opacity,transparent:m.transparent}}return s}
function applySnapshot(s:ObjectSnapshot){s.object.position.copy(s.position);s.object.quaternion.copy(s.quaternion);s.object.scale.copy(s.scale);if(s.object instanceof THREE.Mesh&&s.material){const m=materialFor(s.object);if(m){m.color.set(s.material.color);m.roughness=s.material.roughness;m.metalness=s.material.metalness;m.opacity=s.material.opacity;m.transparent=s.material.transparent;m.needsUpdate=true}}s.object.updateMatrixWorld(true)}
function sameSnapshot(a:ObjectSnapshot,b:ObjectSnapshot){return a.position.equals(b.position)&&a.quaternion.equals(b.quaternion)&&a.scale.equals(b.scale)&&JSON.stringify(a.material)===JSON.stringify(b.material)}
function Cube({selected,onSelect}:{selected:boolean;onSelect:(o:THREE.Object3D)=>void}){return <mesh name="Cube" position={[0,1,0]} onClick={e=>{e.stopPropagation();onSelect(e.object)}}><boxGeometry args={[2,2,2]}/><meshStandardMaterial color={selected?'#22c55e':'#4f46e5'} roughness={.35} metalness={.15}/></mesh>}
function GLTFModel({url,onSelect,onLoaded,onAnimations}:ModelProps){const{scene,animations}=useGLTF(url,true,true,configureLoader);useEffect(()=>{scene.traverse(o=>{if(o instanceof THREE.Mesh){o.userData.editorSelectable=true;o.castShadow=true;o.receiveShadow=true}});onLoaded(scene);onAnimations(animations)},[scene,animations,onLoaded,onAnimations]);return <primitive object={scene} onClick={(e:ThreeEvent<MouseEvent>)=>{e.stopPropagation();if(e.object instanceof THREE.Mesh)onSelect(e.object)}}/>}
function SceneSettings(p:SceneSettingsProps){const{camera}=useThree();useEffect(()=>{if(camera instanceof THREE.PerspectiveCamera){camera.fov=p.fov;camera.updateProjectionMatrix()}},[camera,p.fov]);useEffect(()=>{camera.position.set(5,3.5,7);camera.lookAt(0,0,0)},[camera,p.resetCamera]);return <><ambientLight intensity={p.ambientIntensity}/><directionalLight position={p.keyLightPosition} intensity={p.keyLightIntensity} castShadow/><directionalLight position={[-4,3,-4]} intensity={p.fillLightIntensity}/>{p.environmentEnabled&&<Environment key={p.environmentPreset} preset={p.environmentPreset} environmentIntensity={p.environmentIntensity}/>}</>}
function FocusSelected({selected,focusToken}:{selected:SelectedObject|null;focusToken:number}){const{camera,controls}=useThree();useEffect(()=>{if(!selected||!focusToken)return;const box=new THREE.Box3().setFromObject(selected);if(box.isEmpty())return;const size=box.getSize(new THREE.Vector3());const center=box.getCenter(new THREE.Vector3());const maxSize=Math.max(size.x,size.y,size.z,.001);const distance=(maxSize/(2*Math.tan(THREE.MathUtils.degToRad(camera instanceof THREE.PerspectiveCamera?camera.fov:50)/2)))*1.55;const direction=new THREE.Vector3().subVectors(camera.position,center).normalize();if(direction.lengthSq()<.01)direction.set(.55,.35,1).normalize();camera.position.copy(center).add(direction.multiplyScalar(distance));camera.near=Math.max(maxSize/1000,.001);camera.far=Math.max(maxSize*100,100);camera.updateProjectionMatrix();if(controls&&'target' in controls){const target=controls.target as THREE.Vector3;target.copy(center);(controls as any).update()}},[camera,controls,focusToken,selected]);return null}
function AnimationController({scene,clips,index,playing,speed,seekTime,onTime}:{scene:THREE.Object3D|null;clips:THREE.AnimationClip[];index:number;playing:boolean;speed:number;seekTime:number|null;onTime:(time:number)=>void}){
 const mixer=useRef<THREE.AnimationMixer|null>(null),action=useRef<THREE.AnimationAction|null>(null),lastReported=useRef(-1)
 useEffect(()=>{if(!scene||!clips.length){mixer.current=null;action.current=null;return};const m=new THREE.AnimationMixer(scene);mixer.current=m;const a=m.clipAction(clips[index]??clips[0]);a.reset().setLoop(THREE.LoopRepeat,Infinity);a.timeScale=speed;if(playing)a.play();action.current=a;lastReported.current=-1;return()=>{m.stopAllAction();m.uncacheRoot(scene);mixer.current=null;action.current=null}},[scene,clips,index])
 useEffect(()=>{if(action.current)action.current.timeScale=speed},[speed])
 useEffect(()=>{if(!action.current||seekTime===null)return;action.current.time=THREE.MathUtils.clamp(seekTime,0,clips[index]?.duration??0);action.current.paused=!playing;onTime(action.current.time)},[seekTime,clips,index,playing,onTime])
 useEffect(()=>{if(!action.current)return;playing?action.current.play():action.current.paused=true},[playing])
 useFrame((_,delta)=>{if(!mixer.current||!action.current)return;mixer.current.update(delta);const d=clips[index]?.duration??0;const t=d?((action.current.time%d)+d)%d:0;if(Math.abs(t-lastReported.current)>.1){lastReported.current=t;onTime(t)}})
 return null
}
function getMeshNodes(scene:THREE.Object3D){const a:THREE.Mesh[]=[];scene.traverse(o=>{if(o instanceof THREE.Mesh)a.push(o)});return a}
function getHierarchy(scene:THREE.Object3D){const a:{object:THREE.Object3D;depth:number}[]=[];const walk=(o:THREE.Object3D,d:number)=>{a.push({object:o,depth:d});o.children.forEach(c=>walk(c,d+1))};scene.children.forEach(c=>walk(c,0));return a}
function nodeIcon(o:THREE.Object3D){return o instanceof THREE.Mesh?'◇':o instanceof THREE.Bone?'🦴':o instanceof THREE.Camera?'◉':'▸'}
function displayName(o:THREE.Object3D){return o.name||o.type}
function downloadText(filename:string,content:string,type:string){const blob=new Blob([content],{type});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=filename;a.click();URL.revokeObjectURL(u)}
function downloadGlb(target:THREE.Object3D){new GLTFExporter().parse(target,r=>{const b=r instanceof ArrayBuffer?new Blob([r],{type:'model/gltf-binary'}):new Blob([JSON.stringify(r)],{type:'model/gltf+json'});const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='three-playground.glb';a.click();URL.revokeObjectURL(u)},e=>window.alert(`GLB export failed: ${e}`),{binary:true,onlyVisible:false})}
const t3=(v:THREE.Vector3):[number,number,number]=>[v.x,v.y,v.z];const t4=(v:THREE.Quaternion):[number,number,number,number]=>[v.x,v.y,v.z,v.w]
function projectObject(mesh:THREE.Mesh,key:string):ProjectObject{const m=materialFor(mesh);return{key,position:t3(mesh.position),quaternion:t4(mesh.quaternion),scale:t3(mesh.scale),...(m?{material:{color:`#${m.color.getHexString()}`,roughness:m.roughness,metalness:m.metalness,opacity:m.opacity}}:{})}}

export default function App(){
 const[selected,setSelected]=useState<SelectedObject|null>(null),[modelUrl,setModelUrl]=useState(''),[urlInput,setUrlInput]=useState(''),[modelName,setModelName]=useState(''),[mode,setMode]=useState<TransformMode>('translate'),[space,setSpace]=useState<TransformSpace>('world'),[modelMeshes,setModelMeshes]=useState<THREE.Mesh[]>([]),[modelScene,setModelScene]=useState<THREE.Object3D|null>(null),[exportTarget,setExportTarget]=useState<THREE.Object3D|null>(null),[materialVersion,setMaterialVersion]=useState(0),[historyVersion,setHistoryVersion]=useState(0),[fov,setFov]=useState(50),[resetCamera,setResetCamera]=useState(0),[focusToken,setFocusToken]=useState(0),[ambientIntensity,setAmbientIntensity]=useState(.55),[keyLightIntensity,setKeyLightIntensity]=useState(2),[keyLightX,setKeyLightX]=useState(5),[keyLightY,setKeyLightY]=useState(8),[keyLightZ,setKeyLightZ]=useState(5),[fillLightIntensity,setFillLightIntensity]=useState(.5),[environmentEnabled,setEnvironmentEnabled]=useState(true),[environmentPreset,setEnvironmentPreset]=useState<EnvironmentPreset>('studio'),[environmentIntensity,setEnvironmentIntensity]=useState(.7),[projectMessage,setProjectMessage]=useState(''),[hierarchyVersion,setHierarchyVersion]=useState(0),[inspectorVersion,setInspectorVersion]=useState(0),[nameEdit,setNameEdit]=useState(''),[libraryQuery,setLibraryQuery]=useState(''),[libraryFormat,setLibraryFormat]=useState<'ALL'|'GLB'|'GLTF'>('ALL'),[animationClips,setAnimationClips]=useState<THREE.AnimationClip[]>([]),[animationIndex,setAnimationIndex]=useState(0),[animationPlaying,setAnimationPlaying]=useState(true),[animationSpeed,setAnimationSpeed]=useState(1),[animationTime,setAnimationTime]=useState(0),[animationSeekTime,setAnimationSeekTime]=useState<number|null>(null)
 const undoStack=useRef<HistoryEntry[]>([]),redoStack=useRef<HistoryEntry[]>([]),materialHistoryBefore=useRef<ObjectSnapshot|null>(null),transformHistoryBefore=useRef<ObjectSnapshot|null>(null),pendingProject=useRef<ProjectFile|null>(null)
 const pushHistory=useCallback((before:ObjectSnapshot,after:ObjectSnapshot)=>{if(sameSnapshot(before,after))return;undoStack.current.push({before,after});redoStack.current=[];setHistoryVersion(v=>v+1)},[])
 const undo=useCallback(()=>{const e=undoStack.current.pop();if(!e)return;const cur=captureSnapshot(e.before.object);applySnapshot(e.before);redoStack.current.push({before:cur,after:e.before});setHistoryVersion(v=>v+1);setMaterialVersion(v=>v+1);setInspectorVersion(v=>v+1);setHierarchyVersion(v=>v+1)},[])
 const redo=useCallback(()=>{const e=redoStack.current.pop();if(!e)return;const cur=captureSnapshot(e.after.object);applySnapshot(e.after);undoStack.current.push({before:cur,after:e.after});setHistoryVersion(v=>v+1);setMaterialVersion(v=>v+1);setInspectorVersion(v=>v+1);setHierarchyVersion(v=>v+1)},[])
 useEffect(()=>{const k=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||e.target instanceof HTMLSelectElement)return;const x=e.key.toLowerCase();if((e.ctrlKey||e.metaKey)&&x==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if((e.ctrlKey||e.metaKey)&&x==='y'){e.preventDefault();redo();return}if(x==='w')setMode('translate');else if(x==='e')setMode('rotate');else if(x==='r')setMode('scale');else if(x==='q')setSpace(v=>v==='world'?'local':'world');else if(x==='f'&&selected)setFocusToken(v=>v+1);else if(x==='escape')setSelected(null)};window.addEventListener('keydown',k);return()=>window.removeEventListener('keydown',k)},[redo,undo,selected])
 const clearResources=useCallback(()=>{for(const u of new Set(resourceUrls.values()))URL.revokeObjectURL(u);resourceUrls.clear()},[]);useEffect(()=>()=>clearResources(),[clearResources])
 const loadModel=useCallback((url:string,name='Remote model')=>{if(!url)return;setModelUrl(url);setModelName(name);setSelected(null);setModelMeshes([]);setModelScene(null);setExportTarget(null);setAnimationClips([]);setAnimationIndex(0);setAnimationPlaying(true);setAnimationSpeed(1);setAnimationTime(0);setAnimationSeekTime(null);setMaterialVersion(v=>v+1);undoStack.current=[];redoStack.current=[];setHistoryVersion(v=>v+1);setProjectMessage('')},[])
 const handleFiles=(e:ChangeEvent<HTMLInputElement>)=>{const fs=Array.from(e.target.files??[]),main=fs.find(f=>/\.(gltf|glb)$/i.test(f.name));if(!main){if(fs.length)alert('GLB 또는 GLTF 파일을 하나 이상 포함해야 합니다.');e.target.value='';return}clearResources();fs.forEach(f=>{const u=URL.createObjectURL(f);resourceUrls.set(f.name,u);resourceUrls.set(`./${f.name}`,u)});loadModel(resourceUrls.get(main.name)!,main.name);e.target.value=''}
 const handleUrlSubmit=(e:FormEvent)=>{e.preventDefault();clearResources();loadModel(urlInput.trim())};const clearModel=()=>{pendingProject.current=null;clearResources();setModelUrl('');setModelName('');setModelMeshes([]);setModelScene(null);setExportTarget(null);setAnimationClips([]);setAnimationIndex(0);setAnimationPlaying(true);setAnimationSpeed(1);setAnimationTime(0);setAnimationSeekTime(null);setSelected(null);setMaterialVersion(v=>v+1);undoStack.current=[];redoStack.current=[];setHistoryVersion(v=>v+1);setProjectMessage('')}
 const selectedMesh=selected instanceof THREE.Mesh?selected:null,material=selectedMesh?materialFor(selectedMesh):null;void materialVersion;void historyVersion;void hierarchyVersion;void inspectorVersion
 const beginMaterialHistory=()=>{if(selectedMesh)materialHistoryBefore.current=captureSnapshot(selectedMesh)};const endMaterialHistory=()=>{if(!selectedMesh||!materialHistoryBefore.current)return;const b=materialHistoryBefore.current;materialHistoryBefore.current=null;pushHistory(b,captureSnapshot(selectedMesh))};const updateMaterial=(fn:(m:MaterialLike)=>void)=>{if(!material)return;fn(material);material.transparent=material.opacity<1;material.needsUpdate=true;setMaterialVersion(v=>v+1)}
 const beginTransformHistory=()=>{if(selected)transformHistoryBefore.current=captureSnapshot(selected)};const endTransformHistory=()=>{if(!selected||!transformHistoryBefore.current)return;const b=transformHistoryBefore.current;transformHistoryBefore.current=null;pushHistory(b,captureSnapshot(selected));setInspectorVersion(v=>v+1)}
 const updateTransform=(kind:'position'|'rotation'|'scale',axis:'x'|'y'|'z',value:number)=>{if(!selected)return;if(kind==='position')selected.position[axis]=value;if(kind==='rotation')selected.rotation[axis]=THREE.MathUtils.degToRad(value);if(kind==='scale')selected.scale[axis]=value;selected.updateMatrixWorld(true);setInspectorVersion(v=>v+1)}
 const resetTransform=()=>{if(!selected)return;const b=captureSnapshot(selected);selected.position.set(0,0,0);selected.rotation.set(0,0,0);selected.scale.set(1,1,1);selected.updateMatrixWorld(true);pushHistory(b,captureSnapshot(selected));setInspectorVersion(v=>v+1)}
 const renameSelected=()=>{if(!selected)return;const next=nameEdit.trim();if(next&&next!==selected.name){selected.name=next;setHierarchyVersion(v=>v+1)}else setNameEdit(selected.name||'')}
 const toggleVisibility=(o:THREE.Object3D)=>{o.visible=!o.visible;setHierarchyVersion(v=>v+1)}
 const restoreProjectObjects=(objects:ProjectObject[],sceneOverride?:THREE.Object3D)=>{const byKey=new Map<string,THREE.Mesh>();const sourceScene=sceneOverride??modelScene;if(!modelUrl){if(exportTarget instanceof THREE.Mesh)byKey.set('cube',exportTarget)}else if(sourceScene)getMeshNodes(sourceScene).forEach(m=>byKey.set(m.uuid,m));objects.forEach(d=>{const m=byKey.get(d.key);if(!m)return;m.position.set(...d.position);m.quaternion.set(...d.quaternion);m.scale.set(...d.scale);if(d.material){const x=materialFor(m);if(x){x.color.set(d.material.color);x.roughness=d.material.roughness;x.metalness=d.material.metalness;x.opacity=d.material.opacity;x.transparent=x.opacity<1;x.needsUpdate=true}}m.updateMatrixWorld(true)});setMaterialVersion(v=>v+1);setInspectorVersion(v=>v+1)}
 const applyProjectSettings=(p:ProjectFile)=>{setFov(p.scene.fov);setAmbientIntensity(p.scene.ambientIntensity);setKeyLightIntensity(p.scene.keyLightIntensity);setKeyLightX(p.scene.keyLightPosition[0]);setKeyLightY(p.scene.keyLightPosition[1]);setKeyLightZ(p.scene.keyLightPosition[2]);setFillLightIntensity(p.scene.fillLightIntensity);setEnvironmentEnabled(p.scene.environmentEnabled);setEnvironmentPreset(p.scene.environmentPreset);setEnvironmentIntensity(p.scene.environmentIntensity)}
 const applyProject=(p:ProjectFile)=>{applyProjectSettings(p);setTimeout(()=>restoreProjectObjects(p.scene.objects),0);setProjectMessage('프로젝트 불러오기 완료')};const handleProjectFile=(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];e.target.value='';if(!f)return;const r=new FileReader();r.onload=()=>{try{const p=JSON.parse(String(r.result)) as ProjectFile;if(p?.type!=='three-playground-project'||p.version!==1)throw new Error('지원하지 않는 프로젝트 파일입니다.');if(p.model?.source==='url'&&p.model.url&&p.model.url!==modelUrl){pendingProject.current=p;clearResources();setUrlInput(p.model.url);loadModel(p.model.url,p.model.name||'Remote model');return}applyProject(p)}catch(err){alert(err instanceof Error?err.message:'프로젝트 파일을 읽을 수 없습니다.')}};r.readAsText(f)}
 useEffect(()=>{const p=pendingProject.current;if(!modelScene||!p)return;pendingProject.current=null;applyProjectSettings(p);restoreProjectObjects(p.scene.objects,modelScene);setProjectMessage('프로젝트 불러오기 완료')},[modelScene])
 const handleSelect=(o:THREE.Object3D)=>{setSelected(o);setNameEdit(o.name||'');if(!modelUrl)setExportTarget(o)};const handleModelLoaded=useCallback((s:THREE.Object3D)=>{setModelScene(s);setExportTarget(s);setModelMeshes(getMeshNodes(s));setHierarchyVersion(v=>v+1)},[]);const handleAnimations=useCallback((clips:THREE.AnimationClip[])=>{setAnimationClips(clips);setAnimationIndex(0);setAnimationPlaying(clips.length>0)},[]);
 const handleTransformStart=(o:THREE.Object3D)=>{transformHistoryBefore.current=captureSnapshot(o);o.userData.historyBefore=transformHistoryBefore.current};const handleTransformEnd=(o:THREE.Object3D)=>{const b=transformHistoryBefore.current??o.userData.historyBefore as ObjectSnapshot|undefined;transformHistoryBefore.current=null;delete o.userData.historyBefore;if(b)pushHistory(b,captureSnapshot(o));setInspectorVersion(v=>v+1)}
 const saveProject=()=>{const objects:ProjectObject[]=[];if(!modelUrl){const c=exportTarget instanceof THREE.Mesh?exportTarget:null;if(c)objects.push(projectObject(c,'cube'))}else modelMeshes.forEach(m=>objects.push(projectObject(m,m.uuid)));const p:ProjectFile={version:1,type:'three-playground-project',savedAt:new Date().toISOString(),...(modelUrl?{model:{source:'url',url:modelUrl,name:modelName||'Remote model'}}:{}),scene:{fov,ambientIntensity,keyLightIntensity,keyLightPosition:[keyLightX,keyLightY,keyLightZ],fillLightIntensity,environmentEnabled,environmentPreset,environmentIntensity,objects}};downloadText('three-playground.project.json',JSON.stringify(p,null,2),'application/json');setProjectMessage('프로젝트 저장 완료')}
 const tree=modelScene?getHierarchy(modelScene):[]
 const activeAnimation=animationClips[animationIndex]??animationClips[0]??null
 const handleAnimationSeek=(value:number)=>{setAnimationPlaying(false);setAnimationSeekTime(value);setAnimationTime(value)}
 const reportAnimationTime=useCallback((time:number)=>setAnimationTime(time),[])
 const normalizedQuery=libraryQuery.trim().toLowerCase();const filteredModels=publicModels.filter(model=>model.name!=='Animated Triangle'&&model.name!=='Cameras'&&(libraryFormat==='ALL'||model.format===libraryFormat)&&(!normalizedQuery||`${model.name} ${model.description} ${model.format}`.toLowerCase().includes(normalizedQuery)))
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><strong>Three Playground</strong><span>3D Scene Editor</span></div>
 <section className="panel"><span className="section-label">Model</span><label className="file-input">GLB / GLTF + 리소스 업로드<input type="file" accept=".glb,.gltf,.bin,.png,.jpg,.jpeg,.webp,.ktx2" multiple onChange={handleFiles}/></label><small>.gltf, .bin, 텍스처를 함께 선택하세요.</small><form onSubmit={handleUrlSubmit} className="url-form"><input value={urlInput} onChange={e=>setUrlInput(e.target.value)} placeholder="GLB / GLTF URL"/><button type="submit">Load</button></form>{modelUrl&&<div className="loaded-model"><span>{modelName||'Model loaded'}</span><button onClick={clearModel}>Clear</button></div>}<div className="public-models"><div className="library-heading"><span>Public Library</span><small>{filteredModels.length}/{publicModels.length}</small></div><div className="library-search"><input value={libraryQuery} onChange={e=>setLibraryQuery(e.target.value)} placeholder="Search models..." aria-label="Search public models"/><button aria-label="Clear model search" onClick={()=>setLibraryQuery('')} disabled={!libraryQuery}>×</button></div><div className="library-filters"><button className={libraryFormat==='ALL'?'active':''} onClick={()=>setLibraryFormat('ALL')}>All</button><button className={libraryFormat==='GLB'?'active':''} onClick={()=>setLibraryFormat('GLB')}>GLB</button><button className={libraryFormat==='GLTF'?'active':''} onClick={()=>setLibraryFormat('GLTF')}>GLTF</button></div>{filteredModels.length===0?<span className="empty-library">No matching models.</span>:filteredModels.map(model=><button key={model.url} className={modelUrl===model.url?'public-model active':'public-model'} onClick={()=>{clearResources();setUrlInput(model.url);loadModel(model.url,model.name)}}><span className="public-model-main"><strong>{model.name}</strong><small>{model.description}</small></span><span className="model-format">{model.format}</span></button>)}</div></section>
 {modelUrl&&<section className="panel hierarchy"><span className="section-label">Scene Hierarchy</span><button className={!selected?'scene-item active':'scene-item'} onClick={()=>setSelected(null)}>◈ {modelName||'Scene'}</button>{tree.length===0?<span className="empty-hierarchy">모델 로딩 중...</span>:tree.map(({object,depth})=><div key={object.uuid} className={selected===object?'scene-row active':'scene-row'} style={{paddingLeft:`${6+depth*14}px`}}><button className="scene-item tree-select" title={`${object.type}: ${displayName(object)}`} onClick={()=>handleSelect(object)}><span>{nodeIcon(object)}</span><span>{displayName(object)}</span></button><button className="visibility-button" title={object.visible?'Hide':'Show'} onClick={()=>toggleVisibility(object)}>{object.visible?'●':'○'}</button></div>)}</section>}
 <section className="panel"><span className="section-label">History</span><div className="button-row"><button onClick={undo} disabled={!undoStack.current.length}>Undo</button><button onClick={redo} disabled={!redoStack.current.length}>Redo</button></div><small>Ctrl/Cmd+Z · Ctrl/Cmd+Y</small></section>
 <section className="panel"><span className="section-label">Transform</span>{selected?<><label>Name <div className="inline-control"><input value={nameEdit} onChange={e=>setNameEdit(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')renameSelected()}} onBlur={renameSelected}/><button onClick={renameSelected}>Set</button></div></label><div className="button-row"><button className={mode==='translate'?'active':''} onClick={()=>setMode('translate')}>W Move</button><button className={mode==='rotate'?'active':''} onClick={()=>setMode('rotate')}>E Rotate</button><button className={mode==='scale'?'active':''} onClick={()=>setMode('scale')}>R Scale</button></div><button className="wide-button" onClick={()=>setSpace(v=>v==='world'?'local':'world')}>Q · {space} space</button><button className="wide-button" onClick={()=>setFocusToken(v=>v+1)}>F · Focus selected</button><div className="transform-grid"><span></span><span>X</span><span>Y</span><span>Z</span><span>Position</span>{(['x','y','z'] as const).map(axis=><span key={axis}><input aria-label={`Position ${axis}`} type="number" step="0.01" value={selected.position[axis].toFixed(3)} onFocus={beginTransformHistory} onChange={e=>updateTransform('position',axis,+e.target.value)} onBlur={endTransformHistory}/></span>)}<span>Rotation°</span>{(['x','y','z'] as const).map(axis=><span key={axis}><input aria-label={`Rotation ${axis}`} type="number" step="1" value={THREE.MathUtils.radToDeg(selected.rotation[axis]).toFixed(1)} onFocus={beginTransformHistory} onChange={e=>updateTransform('rotation',axis,+e.target.value)} onBlur={endTransformHistory}/></span>)}<span>Scale</span>{(['x','y','z'] as const).map(axis=><span key={axis}><input aria-label={`Scale ${axis}`} type="number" step="0.01" min="0.001" value={selected.scale[axis].toFixed(3)} onFocus={beginTransformHistory} onChange={e=>updateTransform('scale',axis,+e.target.value)} onBlur={endTransformHistory}/></span>)}</div><button className="wide-button" onClick={resetTransform}>Reset transform</button><small>{selected.name||'Selected object'} · {selected.type}</small></>:<small>Hierarchy에서 오브젝트를 선택하세요.</small>}</section>
 <section className="panel"><span className="section-label">Material</span>{material?<><label>Color <input type="color" value={`#${material.color.getHexString()}`} onPointerDown={beginMaterialHistory} onPointerUp={endMaterialHistory} onChange={e=>updateMaterial(m=>m.color.set(e.target.value))}/></label><label>Roughness <input type="range" min="0" max="1" step="0.01" value={material.roughness} onPointerDown={beginMaterialHistory} onPointerUp={endMaterialHistory} onChange={e=>updateMaterial(m=>m.roughness=+e.target.value)}/><output>{material.roughness.toFixed(2)}</output></label><label>Metalness <input type="range" min="0" max="1" step="0.01" value={material.metalness} onPointerDown={beginMaterialHistory} onPointerUp={endMaterialHistory} onChange={e=>updateMaterial(m=>m.metalness=+e.target.value)}/><output>{material.metalness.toFixed(2)}</output></label><label>Opacity <input type="range" min="0" max="1" step="0.01" value={material.opacity} onPointerDown={beginMaterialHistory} onPointerUp={endMaterialHistory} onChange={e=>updateMaterial(m=>m.opacity=+e.target.value)}/><output>{material.opacity.toFixed(2)}</output></label><small>Material 변경도 Undo/Redo에 기록됩니다.</small></>:<small>Mesh를 선택하면 Material Editor가 활성화됩니다.</small>}</section>
 <section className="panel"><span className="section-label">Animation</span>{animationClips.length&&activeAnimation?<><div className="animation-controls"><button onClick={()=>setAnimationPlaying(v=>!v)}>{animationPlaying?'Pause':'Play'}</button><button onClick={()=>{setAnimationPlaying(false);setAnimationSeekTime(0);setAnimationTime(0)}}>↺</button><select value={animationIndex} onChange={e=>{setAnimationIndex(+e.target.value);setAnimationTime(0);setAnimationSeekTime(0);setAnimationPlaying(true)}}>{animationClips.map((clip,i)=><option key={clip.name+'-'+i} value={i}>{clip.name||'Animation '+(i+1)}</option>)}</select></div><label>Speed <input type="range" min="0.1" max="2" step="0.1" value={animationSpeed} onChange={e=>setAnimationSpeed(+e.target.value)}/><output>{animationSpeed.toFixed(1)}×</output></label><label>Timeline <input type="range" min="0" max={activeAnimation.duration} step="0.01" value={Math.min(animationTime,activeAnimation.duration)} onChange={e=>handleAnimationSeek(+e.target.value)} onPointerUp={()=>setAnimationPlaying(true)}/><output>{animationTime.toFixed(2)} / {activeAnimation.duration.toFixed(2)}s</output></label><small>{animationClips.length} clip{animationClips.length===1?'':'s'} · {activeAnimation.name||'Animation '+(animationIndex+1)}</small></>:<small>이 모델에는 Animation Clip이 없습니다.</small>}</section><section className="panel"><span className="section-label">Camera</span><label>FOV <input type="range" min="20" max="100" value={fov} onChange={e=>setFov(+e.target.value)}/><output>{fov}°</output></label><button className="wide-button" onClick={()=>setResetCamera(v=>v+1)}>Reset camera</button></section>
 <section className="panel"><span className="section-label">Lighting</span><label>Ambient <input type="range" min="0" max="2" step=".05" value={ambientIntensity} onChange={e=>setAmbientIntensity(+e.target.value)}/><output>{ambientIntensity.toFixed(2)}</output></label><label>Key <input type="range" min="0" max="5" step=".1" value={keyLightIntensity} onChange={e=>setKeyLightIntensity(+e.target.value)}/><output>{keyLightIntensity.toFixed(1)}</output></label><label>Fill <input type="range" min="0" max="3" step=".1" value={fillLightIntensity} onChange={e=>setFillLightIntensity(+e.target.value)}/><output>{fillLightIntensity.toFixed(1)}</output></label></section>
 <section className="panel"><span className="section-label">Environment</span><label className="checkbox"><input type="checkbox" checked={environmentEnabled} onChange={e=>setEnvironmentEnabled(e.target.checked)}/> HDRI</label><select value={environmentPreset} onChange={e=>setEnvironmentPreset(e.target.value as EnvironmentPreset)}>{(['studio','city','sunset','dawn','night','warehouse','forest','apartment'] as EnvironmentPreset[]).map(x=><option key={x}>{x}</option>)}</select><label>Intensity <input type="range" min="0" max="2" step=".05" value={environmentIntensity} onChange={e=>setEnvironmentIntensity(+e.target.value)}/><output>{environmentIntensity.toFixed(2)}</output></label></section>
 <section className="panel"><span className="section-label">Project</span><div className="button-row"><button onClick={saveProject}>Save JSON</button><label className="file-button">Load JSON<input type="file" accept="application/json,.json" onChange={handleProjectFile}/></label></div>{projectMessage&&<small>{projectMessage}</small>}</section><section className="panel"><span className="section-label">Export</span><button className="wide-button" disabled={!exportTarget} onClick={()=>exportTarget&&downloadGlb(exportTarget)}>Export GLB</button></section><small className="help">W/E/R: transform · Q: world/local · F: focus · Esc: deselect</small>
 </aside><main className="viewport"><Canvas camera={{position:[5,3.5,7],fov}} shadows onPointerMissed={()=>setSelected(null)}><color attach="background" args={['#0b1020']}/><SceneSettings fov={fov} resetCamera={resetCamera} ambientIntensity={ambientIntensity} keyLightIntensity={keyLightIntensity} keyLightPosition={[keyLightX,keyLightY,keyLightZ]} fillLightIntensity={fillLightIntensity} environmentEnabled={environmentEnabled} environmentPreset={environmentPreset} environmentIntensity={environmentIntensity}/><FocusSelected selected={selected} focusToken={focusToken}/><AnimationController scene={modelScene} clips={animationClips} index={animationIndex} playing={animationPlaying} speed={animationSpeed} seekTime={animationSeekTime} onTime={reportAnimationTime}/>
            <KeyframeTimeline selected={selected} />{!modelUrl&&<Cube selected={selected?.name==='Cube'} onSelect={handleSelect}/>} {modelUrl&&<Suspense fallback={null}><Bounds fit clip observe margin={1.2}><GLTFModel url={modelUrl} onSelect={handleSelect} onLoaded={handleModelLoaded} onAnimations={handleAnimations}/></Bounds></Suspense>}{selectedMesh&&<TransformControls object={selectedMesh} mode={mode} space={space} onMouseDown={()=>handleTransformStart(selectedMesh)} onMouseUp={()=>handleTransformEnd(selectedMesh)}/>}<Grid args={[20,20]} cellSize={1} cellThickness={.6} sectionSize={5} sectionThickness={1.2} fadeDistance={30} infiniteGrid/><OrbitControls makeDefault enableDamping/></Canvas></main></div>
}
